
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int s_flecha = 7;
  public static final int llave_cerrada = 4;
  public static final int coma = 10;
  public static final int numero = 2;
  public static final int s_interrogacion = 15;
  public static final int s_frase = 23;
  public static final int espacio = 20;
  public static final int virgilla = 9;
  public static final int conj_sym = 21;
  public static final int or = 12;
  public static final int fin_linea = 16;
  public static final int dos_puntos = 5;
  public static final int punto = 11;
  public static final int ident = 22;
  public static final int range = 19;
  public static final int EOF = 0;
  public static final int letra = 24;
  public static final int error = 1;
  public static final int llave_abierta = 3;
  public static final int s_comilla = 17;
  public static final int asterisco = 13;
  public static final int s_porcentaje = 8;
  public static final int punto_coma = 6;
  public static final int doble_comilla = 18;
  public static final int s_mas = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero",
  "llave_abierta",
  "llave_cerrada",
  "dos_puntos",
  "punto_coma",
  "s_flecha",
  "s_porcentaje",
  "virgilla",
  "coma",
  "punto",
  "or",
  "asterisco",
  "s_mas",
  "s_interrogacion",
  "fin_linea",
  "s_comilla",
  "doble_comilla",
  "range",
  "espacio",
  "conj_sym",
  "ident",
  "s_frase",
  "letra"
  };
}

